name: GCEL CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: nvidia/cuda:11.7.1-cudnn8-devel-ubuntu20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build and Test
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        ctest -R AccTest # 运行测试
